import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/footer";
import Comment from "../components/comment";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
        <title>Frontend Mentor | Interactive comments section</title>
      </Head>
      <Comment />
      <Footer />
    </div>
  );
};

export default Home;
